### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by zlshames** [zlshames/YNAB-Copilot#1]
- [ ] Riverpod for State Management
- [ ] Average monthly Spend
    - See how much your monthly spending has changed over time
- [ ] Category spending over time (1 year)
    - See the change in how much you've spent over time for a specific category
- [ ] Payee spending over time (per month)
    - See how much you've spent at a specific vendor over time
- [ ] Category spend details
    - [ ] daily spend for the category: line/bar chart
    - [ ] spending by payee breakdown: pie chart
- [ ] Rule 4: financial independence forecasting
    - https://beyondrule4.jmmorrissey.com/forecasting
- [ ] alerts (in app only, due to token expiration) for unusual spending habits
- [ ] API key login for background activity
- [ ] data storage & incremental sync
- [ ] weekly/monthly reports
- [ ] net worth tracker
- [ ] cross platform app
- [ ] dashboards
